roles:
  - name: common
    src: https://github.com/escalate/ansible-raspberry-common.git
    scm: git

  - name: docker
    src: https://github.com/escalate/ansible-raspberry-docker.git
    scm: git
