- name: Create read-only directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ traefik_etc_path }}"

- name: Create service configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_etc_path }}/traefik.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart traefik service

- name: Define environment variables
  ansible.builtin.template:
    src: traefik.env.j2
    dest: "{{ traefik_etc_path }}/traefik.env"
    owner: root
    group: root
    mode: 0644
  notify: Restart traefik service

- name: Define Docker container labels
  ansible.builtin.template:
    src: traefik.label.j2
    dest: "{{ traefik_etc_path }}/traefik.label"
    owner: root
    group: root
    mode: 0644
  notify: Restart traefik service

- name: Pull Docker image
  community.general.docker_image:
    name: "traefik:{{ traefik_docker_image_version }}"
    source: pull

- name: Create systemd service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: 0644
  notify: Restart traefik service

- name: Start and enable service
  ansible.builtin.systemd:
    name: traefik
    state: started
    enabled: true
    daemon_reload: true

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Wait for service to become available
  ansible.builtin.uri:
    url: http://localhost:8080/api/version
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
