- name: Converge
  hosts: all
  vars:
    traefik_docker_image_version: latest
    traefik_docker_memory: 1G
    traefik_docker_labels:
      maintainer: me@example.com
    traefik_etc_path: /etc/traefik
    traefik_config:
      global:
        checkNewVersion: false
        sendAnonymousUsage: false
      log:
        level: INFO
      api:
        insecure: true
      entryPoints:
        web:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
        websecure:
          address: ":443"
      providers:
        docker:
          defaultRule: Host(`{{ '{{' }} trimPrefix `/` .Name {{ '}}' }}.docker.localhost`)
      accessLog: {}
    traefik_env_vars:
      TRAEFIK_API_DEBUG: true
  roles:
    - role: ansible-raspberry-traefik-proxy-docker
      tags: traefik
